### ISSUE TITLE
Undefined reference trying to compile README example

### ISSUE THREAD

**Issue by rcorre** [elvisxzhou/artemisd#15]
I'm getting the following when trying to run the README example on linux:

```
In function 
`nothrow artemisd.aspect.Aspect artemisd.aspect.Aspect.all!(app.Position, app.Velocity).all()':
...
source/artemisd/aspect.d:39: undefined reference to 
`nothrow void artemisd.aspect.set!(std.bitmanip.BitArray artemisd.aspect.Aspect.allSet, app.Position, app.Velocity).set()'
```

DMD v2.067

**Comment by elvisxzhou** [comment]
Seems like a compiler bug.
I've filed a bug report, see https://issues.dlang.org/show_bug.cgi?id=14588

**Comment by rcorre** [comment]
Thanks for that minimized test case. Hopefully that will help track down the issue.

**Comment by elvisxzhou** [comment]
It compiles and links successfully now with dmd-2.068.0-b2.
